//! Where this module gets random bytes, which is nowhere.
//!
//! Nothing on the path from a receipt to a verdict asks for one. Checking a signature is arithmetic
//! over bytes that already exist: the nonce was generated by whoever fetched the attestation, years
//! ago, and it is carried inside the receipt. A verifier that needed entropy would be doing something
//! other than verifying.
//!
//! The reason this file exists at all is that a signature library further down the tree links the
//! crate that supplies randomness whether or not it calls it, and on this target that crate will not
//! compile until it is told where randomness comes from. There are two ways to tell it. One brings a
//! binding generator in, which puts an import on the module and stops it loading in a plain
//! WebAssembly engine, and takes away the property that the whole page is built for. The other is
//! this: register a source that refuses.
//!
//! Refusing is the honest answer rather than a corner cut. A weak source that quietly returned
//! zeroes would compile the same, run the same, and be a real fault the day somebody used this
//! module for something that does need entropy. A refusal is loud on the first call and there has
//! never been a first call.

use getrandom::register_custom_getrandom;

/// Always an error, and the error code says why.
fn there_is_no_randomness_here(_destination: &mut [u8]) -> Result<(), getrandom::Error> {
    Err(getrandom::Error::UNSUPPORTED)
}

// The macro this expands to exports a function, which is the same unsafe attribute the four
// boundary functions carry, for the same reason.
#[allow(
    unsafe_code,
    reason = "registering a source expands to an exported function"
)]
mod registered {
    use super::there_is_no_randomness_here;
    super::register_custom_getrandom!(there_is_no_randomness_here);
}
