#!/usr/bin/env python3
"""Say whether the signing route's two self-tests notice each of their clauses taken away.

`scripts/the-binaries-are-signed.py --self-test` stands between a change to the signature check and
a release that trusts it, and `scripts/the-release-route-holds.py --self-test` between a change to the
route check and a setting that moves unnoticed. A self-test that stays green with a clause deleted is
not holding that clause, and nothing else would notice until a binary signed by somebody else passed
or the route widened. So this copies both checks, with the workflows the route check reads, to a
scratch folder, removes one clause at a time, and runs the self-test of the check it was removed
from on each copy. Every copy must fail it.

    python scripts/the-signing-self-test-notices-each-clause-removed.py

Each clause is named by the exact text it is removed from. Where that text is not in the check
exactly once, the clause is reported as MOVED and the run fails, because a clause that has been
rewritten is a clause nobody has shown the self-test holds. Fix the text here in the same change.
Where a clause is a call in the route check's `run()`, taking it away means the call is never made,
which is how a check stops checking without any judgement in it changing.

It prints a line per clause, CAUGHT, MISSED, CRASHED or MOVED, and exits 0 only when both untouched checks
pass their self-tests and every clause is CAUGHT. The copies run a few at a time, as many as
`TW_CLAUSE_WORKERS` says and four where it says nothing.
"""

import concurrent.futures
import os
import shutil
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
SIGNATURE_CHECK = "the-binaries-are-signed.py"
ROUTE_CHECK = "the-release-route-holds.py"

# What each clause of the signature check is, the text it lives in, and what that text becomes
# without it.
SIGNATURE_CLAUSES = [
    ("Windows: the certificate signtool verified is the one inside the file",
     'if not chain or chain[-1].get("sha1") != signer["sha1"]:',
     'if not chain:'),
    ("Windows: the chain ends at our root",
     'elif chain[0]["to"] != w["root"]:',
     'elif False:'),
    ("Windows: our root is the top of the chain, not a name anywhere in it",
     'elif chain[0]["to"] != w["root"]:',
     'elif w["root"] not in [c.get("to") for c in chain]:'),
    ("Windows: the publisher's common name and organisation",
     'if signer["subject_cn"] != [w["subject_common_name"]] or signer["subject_o"] != [w["subject_organisation"]]:',
     'if False:'),
    ("Windows: the publisher's common name",
     'signer["subject_cn"] != [w["subject_common_name"]] or signer["subject_o"]',
     'signer["subject_o"]'),
    ("Windows: the publisher's organisation",
     ' or signer["subject_o"] != [w["subject_organisation"]]:',
     ':'),
    ("Windows: our identity usage",
     'if w["identity_usage"] not in signer["usages"]:',
     'if False:'),
    ("Windows: the publisher and the identity usage, both",
     'if signer["subject_cn"] != [w["subject_common_name"]] or signer["subject_o"] != [w["subject_organisation"]]:',
     'if False:',
     'if w["identity_usage"] not in signer["usages"]:',
     'if False:'),
    ("Windows: the issuer's organisation",
     'if (signer["issuer_o"] != [w["issuer_organisation"]]\n            or ',
     'if ('),
    ("Windows: the issuer's common name",
     '\n            or len(signer["issuer_cn"]) != 1 or not signer["issuer_cn"][0].startswith(w["issuer_common_name_starts"])):',
     '):'),
    ("Windows: signtool verifies it",
     'if code != 0 or "Successfully verified" not in output:\n        return ["signtool verify /pa does not verify it"]',
     'pass'),
    ("Windows: signtool from the Windows Kits folder or a path given, never from the working folder",
     '    if given:\n        return given\n',
     '    if given or shutil.which("signtool"):\n        return given or shutil.which("signtool")\n'),
    ("cosign: only from an absolute folder on the path",
     '        if not os.path.isabs(entry):\n            continue',
     '        if False:\n            continue'),
    ("cosign: never from the folder the check is run in",
     '        if any(same_folder(entry, folder) for folder in avoid):',
     '        if False:'),
    ("cosign: a folder is known by what it is on disk, a link to it and every other spelling included",
     'return os.path.samefile(one, other)',
     'return os.path.normcase(os.path.abspath(one)) == os.path.normcase(os.path.abspath(other))'),
    ("cosign: a folder on the path led by two separators, a share or a device path, is never searched",
     '        if len(entry) > 1 and entry[0] in "\\\\/" and entry[1] in "\\\\/":\n            continue',
     '        if False:\n            continue'),
    ("every archive: a name with a folder or a drive in it is refused as not a plain name",
     '        if odd:\n            raise CouldNotRun(',
     '        if False:\n            raise CouldNotRun('),
    ("every archive: a backslash in a name makes it not a plain name",
     'or "/" in name or "\\\\" in name or',
     'or "/" in name or'),
    ("every archive: a colon in a name makes it not a plain name",
     'or "\\\\" in name or ":" in name:',
     'or "\\\\" in name:'),
    ("a zip: every member's name in front of the file is held to its name in the directory",
     '                with opened.open(member) as each:\n                    each.read(0)',
     '                pass'),
    ("the setting is made before any tool is started, whatever the check is asked",
     '    os.environ["NoDefaultCurrentDirectoryInExePath"] = "1"\n    if args.signtool',
     '    if args.pins:\n        os.environ["NoDefaultCurrentDirectoryInExePath"] = "1"\n    if args.signtool'),
    ("every archive: the binary is written under its own name, not the archive's spelling of it",
     '    path = os.path.join(into, name)\n',
     '    path = os.path.join(into, [entry for entry, _, _, _ in entries if plain_name(entry) == name][0])\n'),
    ("the process tells Windows not to look in the working folder",
     '    os.environ["NoDefaultCurrentDirectoryInExePath"] = "1"',
     '    pass'),
    ("Windows: the newest Kits signtool, by its version read as numbers",
     '    kits = sorted(glob.glob(kits_at), key=version)',
     '    kits = sorted(glob.glob(kits_at))'),
    ("Windows: the newest Kits signtool, not the oldest",
     'return kits[-1] if kits else None',
     'return kits[0] if kits else None'),
    ("macOS: spctl's own exit, and not only what it printed",
     'return code == 0 and "accepted" in output and',
     'return "accepted" in output and'),
    ("cosign: a whole check looks for it that way, and not as Python would",
     'found = tool_on_path("cosign", [os.getcwd()] + ([folder] if folder else []))',
     'found = shutil.which("cosign")'),
    ("macOS: codesign and spctl named where macOS keeps them",
     'CODESIGN, SPCTL = "/usr/bin/codesign", "/usr/sbin/spctl"',
     'CODESIGN, SPCTL = "codesign", "spctl"'),
    ("macOS: codesign --verify has the first word",
     'judge_codesign(code2, out2, pins) if code == 0 else',
     'judge_codesign(code2, out2, pins) if True else'),
    ("macOS: notarised, and not only signed",
     'return code == 0 and "accepted" in output and "source=Notarized Developer ID" in output',
     'return code == 0'),
    ("macOS: our team",
     'if teams != [team]:',
     'if False:'),
    ("macOS: a Developer ID Application certificate of our team",
     'if not authorities or not re.fullmatch(r"Developer ID Application: .+ \\(%s\\)" % re.escape(team), authorities[0]):',
     'if not authorities:'),
    ("macOS: the chain is Apple's",
     'elif authorities[1:] != APPLE_CHAIN:',
     'elif False:'),
    ("every release: nothing a stranger needs is missing",
     '    if missing:\n        say("FAIL", "missing from the release: "',
     '    if False:\n        say("FAIL", "missing from the release: "'),
    ("every archive: its digest is its line in the list",
     'elif listed[name] != digest:',
     'elif False:'),
    ("every archive: each entry is a plain file, not a link",
     '            if not regular:',
     '            if False:'),
    ("every archive: a zip entry marked as a link is one",
     'not i.is_dir() and (i.external_attr >> 16) & 0o170000 in (0, 0o100000)',
     'not i.is_dir()'),
    ("every archive: the binary, LICENSE and NOTICE, each once, and nothing else",
     '        if names != sorted([name, "license", "notice"]):',
     '        if name not in names:'),
    ("every archive: a name led by ./ is the same name",
     '    name = entry[2:] if entry.startswith("./") else entry',
     '    name = entry'),
    ("every archive: no entry larger than a release binary is read",
     '            if size > limit:',
     '            if False:'),
    ("cosign: a batch file never stands in for cosign.exe",
     'file_name = name + ".exe" if exe_only else name',
     'file_name = name + ".cmd" if exe_only else name'),
    ("cosign: never from the folder the assets are read from",
     'found = tool_on_path("cosign", [os.getcwd()] + ([folder] if folder else []))',
     'found = tool_on_path("cosign", [os.getcwd()])'),
    ("Windows: --signtool takes a full path and nothing else",
     'if not (os.path.isabs(value) and os.path.isfile(value)):',
     'if not os.path.isfile(value):'),
    ("Linux: cosign is asked nothing that loosens it, such as skipping the transparency log",
     '"--certificate-oidc-issuer", ISSUER]',
     '"--certificate-oidc-issuer", ISSUER, "--insecure-ignore-tlog"]'),
    ("Linux: cosign verified it",
     'return code == 0 and "Verified OK" in output',
     'return True'),
    ("Linux: the verdict on each bundle is cosign's, not a constant",
     'state = "PASS" if judge_cosign(code, out) else "FAIL"',
     'state = "PASS"'),
    ("Linux: a rehearsal key never passes a release",
     'if rehearsal_key:\n        say("FAIL", "REHEARSAL KEY',
     'if False:\n        say("FAIL", "REHEARSAL KEY'),
    ("Linux: signed with the token of the job that alone enters linux-signing",
     'return subject == LINUX_SUBJECT',
     'return True'),
    ("Linux: the signing job is read for every signature cosign verified",
     'if state == "PASS" and not rehearsal_key:\n                state = check_signing_job(',
     'if False:\n                state = check_signing_job('),
    ("Linux: a bundle carrying a key, or a certificate and a chain, is refused",
     'if kinds == ["certificate"]:',
     'if "certificate" in kinds:'),
    ("Linux: a certificate carrying an extension twice is refused",
     'if oid in found:\n                    raise',
     'if False:\n                    raise'),
    ("Linux: a file with anything beside a bundle's own keys is refused, so cosign and the check read one certificate",
     'if not isinstance(bundle, dict) or not set(bundle) <= BUNDLE_KEYS:',
     'if not isinstance(bundle, dict):'),
    ("Linux: a file whose media type is not a bundle's is refused",
     'if not str(bundle.get("mediaType", "")).startswith(BUNDLE_TYPE):',
     'if False:'),
    ("Linux: the token subject is one UTF8String and nothing after it",
     'if tag != 0x0C or end != len(value):',
     'if False:'),
    ("Linux: an extension is an OID and an OCTET STRING",
     'if parts[0][0] != 0x06 or parts[-1][0] != 0x04:',
     'if False:'),
    ("Linux: a certificate with bytes after it is refused",
     'if end != len(data):\n            raise ValueError("bytes follow the certificate")',
     'if False:\n            raise ValueError("bytes follow the certificate")'),
    ("Linux: signed by the release workflow run from main, and not from a tag",
     'r"@refs/heads/main$")',
     'r"@refs/")'),
    ("Linux: the signer is held from the start of its identity, as cosign finds it anywhere",
     'SIGNER = (r"^https://github',
     'SIGNER = (r"https://github'),
    ("Linux: the signer is this repository's owner",
     'r"^https://github\\.com/Fountech-ai-Limited/timewitness/',
     'r"^https://github\\.com/[^/]+/timewitness/'),
    ("Linux: the signer is this repository",
     'r"^https://github\\.com/Fountech-ai-Limited/timewitness/',
     'r"^https://github\\.com/Fountech-ai-Limited/[^/]+/'),
    ("Linux: the token issuer is GitHub's",
     '\nISSUER = "https://token.actions.githubusercontent.com"',
     '\nISSUER = "https://accounts.google.com"'),
    ("Linux: cosign is told the issuer",
     ', "--certificate-oidc-issuer", ISSUER]',
     ']'),
    ("--version runs only once the target's own clauses passed",
     'return bool(digest) and bool(signature) and all(state == "PASS" for state in clauses)',
     'return True'),
    ("a whole check asks that rule before it runs a binary",
     'if not may_run(digest_of[here], signature_of[here]):',
     'if False:'),
    ("--version runs with no token in its environment",
     'if key.upper() in RUN_ENVIRONMENT]',
     ']'),
    ("the check exits with its verdict",
     '    print(summary(code, results))\n    return code\n',
     '    print(summary(code, results))\n    return 0\n'),
    ("--binary exits 2 where its tool could not be started",
     'results = check_one(args.binary, args.signtool)\n        except CouldNotRun as e:\n            print("NOT RUN: %s" % e)\n            return 2',
     'results = check_one(args.binary, args.signtool)\n        except CouldNotRun as e:\n            print("NOT RUN: %s" % e)\n            return 0'),
    ("--release exits 2 where the release could not be checked",
     'rehearsal_key=args.rehearsal_key, signtool_at=args.signtool)\n        except CouldNotRun as e:\n            print("NOT RUN: %s" % e)\n            return 2',
     'rehearsal_key=args.rehearsal_key, signtool_at=args.signtool)\n        except CouldNotRun as e:\n            print("NOT RUN: %s" % e)\n            return 0'),
    ("cosign missing from this machine is said, not passed over",
     '        say("NOT RUN", "cosign is not on this machine, so the Linux signatures were not checked here")',
     '        pass'),
] + ([
    # Only Windows keeps a device or share prefix in the name a folder resolves to. Elsewhere the
    # resolved name is the folder for every spelling the system gives it, so the two comparisons
    # agree and there is nothing for the self-test to tell apart.
    ("cosign: a folder is known by what it is on disk, not by the text its links resolve to",
     'return os.path.samefile(one, other)',
     'return os.path.normcase(os.path.realpath(one)) == os.path.normcase(os.path.realpath(other))'),
] if os.name == "nt" else [])


def unwired(what):
    """The route check's run() without its call of the clause that starts `what`."""
    call = what.split("(", 1)[0]
    return ("run() makes the call %s" % what[len(call) + 2:], what, "(lambda *a, **k: None)" + what[len(call):])


# The route check's clauses: its judgements, and each call run() makes.
ROUTE_CLAUSES = [
    ("the environment: administrators may not bypass it",
     'if environment.get("can_admins_bypass") is not ENVIRONMENT["can_admins_bypass"]:',
     'if False:'),
    ("the environment: runs from main alone",
     'if named != ENVIRONMENT["branch_policies"]:',
     'if False:'),
    ("a ruleset: who may bypass it",
     'if seen != want["bypass_actors"]:',
     'if False:'),
    ("main: its required check holds everyone",
     'if checks.get("enforcement_level") != want["enforcement_level"]:',
     'if False:'),
    ("the token subject Azure trusts",
     'return [] if subject == OIDC_SUBJECT else',
     'return [] if True else'),
    ("release.yml: started by hand alone",
     'return [] if found == ON_BLOCK else',
     'return [] if True else'),
    ("no other workflow enters an environment",
     '            elif used:\n                problems.append(',
     '            elif False:\n                problems.append('),
    ("release.yml: every action it uses has been read",
     'if used not in RELEASE_ACTIONS:',
     'if False:'),
    ("no job calls a workflow from another repository",
     'if not called.startswith("./"):',
     'if False:'),
    ("who starts a release: the account's number as well as its name",
     'if str(number) != str(known):',
     'if False:'),
    ("who starts a release: nobody not written down",
     '    return ["%s is not one of the accounts written down as starting releases',
     '    return [] and ["%s is not one of the accounts written down as starting releases'),
    ("the guard asks this file who may start a release",
     "if not re.search(r'python3 scripts/the-release-route-holds",
     "if False and not re.search(r'python3 scripts/the-release-route-holds"),
    ("the guard reads the number of the account that started the run",
     "if not re.search(r'actor_id=",
     "if False and not re.search(r'actor_id="),
    ("the guard refuses anybody who does not administer the repository",
     "if not re.search(r'\\[ \"\\$role\" = admin",
     "if False and not re.search(r'\\[ \"\\$role\" = admin"),
    ("the guard asks whether the tag's commit is on main's own commit, as written here",
     'if guard.count(GUARD_ON_MAIN) != 1:',
     'if False:'),
    ("the guard sets the tag's commit, main's commit and the answer once each",
     'if sorted(assigned) != ["commit", "main_commit", "on_main"]:',
     'if False:'),
    ("the guard setting one of them behind export, declare, local or readonly is seen",
     '(?:(?:export|declare|local|readonly)[ \\t]+)?',
     ''),
    ("the guard reading into one of them is refused",
     '    if re.search(r"(?:^|[;&|({]',
     '    if False and re.search(r"(?:^|[;&|({]'),
    ("what is written down refuses every tag outside v* to everybody",
     'if not any(making(r, ["~ALL"], ["refs/tags/v*"], []) for r in rulesets.values()):',
     'if False:'),
    ("what is written down keeps every tag starting v to an administrator",
     'if not any(making(r, ["refs/tags/v*"], [], [dict(ADMIN, bypass_mode="always")]) for r in rulesets.values()):',
     'if False:'),
    ("a tag ruleset counts only on tags",
     'return (ruleset.get("target") == "tag" and ',
     'return ('),
    ("a tag ruleset counts only while it is enforced",
     ' and ruleset.get("enforcement") == "active"',
     ''),
    ("a tag ruleset counts only on the tags it names",
     '\n                and ruleset.get("conditions") == {"ref_name": {"exclude": exclude, "include": include}}',
     ''),
    ("a tag ruleset counts only where it refuses making a tag",
     '\n                and {"type": "creation"} in (ruleset.get("rules") or [])',
     ''),
    ("a tag ruleset counts only with nobody else let round it",
     ' and ruleset.get("bypass_actors") == bypass)',
     ')'),
    ("the ruleset written down refuses every tag outside v*",
     '"conditions": {"ref_name": {"exclude": ["refs/tags/v*"], "include": ["~ALL"]}},',
     '"conditions": {"ref_name": {"exclude": ["refs/tags/*"], "include": ["~ALL"]}},'),
    ("the ruleset written down keeps a pre-release tag to an administrator",
     '"conditions": {"ref_name": {"exclude": [], "include": ["refs/tags/v*"]}},',
     '"conditions": {"ref_name": {"exclude": ["refs/tags/v*-*"], "include": ["refs/tags/v*"]}},'),
    ("the tags are read as a list",
     '    if not isinstance(listed, list):\n        return ["GitHub\'s answer for the repository\'s tags',
     '    if False:\n        return ["GitHub\'s answer for the repository\'s tags'),
    ("no tag stands but one named as a release tag",
     'for t in listed if not (isinstance(t, dict) and re.match(RELEASE_TAG, str(t.get("ref"))))]',
     'for t in listed if False]'),
    ("a standing tag passes only by a release tag's whole name, not by starting v",
     'RELEASE_TAG = r"^refs/tags/v[0-9]+(\\.[0-9]+){0,2}(-[0-9A-Za-z.-]+)?$"',
     'RELEASE_TAG = r"^refs/tags/v"'),
    ("release.yml reads no secret under a name an older run reads",
     'problems = ["release.yml reads %s, a name an older run of it reads too" % n for n in sorted(read & RETIRED_SECRETS)]',
     'problems = []'),
    ("release.yml reads the secrets written down and no others",
     'if read - RETIRED_SECRETS != RELEASE_SECRETS:',
     'if False:'),
    ("Attach is given the commit the guard read",
     'if commit != "${{ needs.tag.outputs.commit }}":',
     'if False:'),
    ("Attach compares the tag's commit with it",
     "            or '[ \"$now\" != \"$COMMIT\" ]' not in text:",
     "            or False:"),
    ("Attach makes a draft, gives it every file, reads the tag again, then publishes",
     'if -1 in at or at != sorted(at) or "gh release create" in text or text.count("-X POST") != 2:',
     'if False:'),
    ("Attach gives files to a release by its number, never by its tag",
     '        problems.append("files are attached by the tag, which another release on it could answer to, and not by number")',
     '        pass'),
    ("the Attach step is held to the byte",
     'return [] if digest == ATTACH_SHA256 else',
     'return [] if True else'),
    ("Attach reads the tag again after uploading to a release that was public already",
     '        problems.append("files attached to a release that was public already are not held to the tag read again")',
     '        pass'),
    ("Attach takes only GitHub's own answer for there being no release",
     '        problems.append("a failure to read the release could be taken for there being none")',
     '        pass'),
    ("Attach takes off its files by the numbers their uploads answered with",
     '        problems.append("a run that stops partway does not take off its files by the numbers their uploads answered with")',
     '        pass'),
    ("Attach looks more than once for a file whose upload got no answer",
     '        problems.append("a run that stops partway reads the release once for a file whose upload got no answer, "',
     '        (lambda *a: None)("a run that stops partway reads the release once for a file whose upload got no answer, "'),
    ("Attach takes off no file somebody else put there under one of its names",
     '        problems.append("a run that stops partway could take off a file somebody else put on the release under one of its names")',
     '        pass'),
    ("Attach takes an upload or a draft as answered only by a number",
     '        problems.append("an upload or a draft is taken as answered by whatever gh printed, which on a failure is GitHub\'s error and not a number")',
     '        pass'),
    ("Attach looks for every upload that got no number back",
     '        problems.append("a run that stops partway could look for none of the uploads that got no number back")',
     '        pass'),
    ("Attach finds a draft whose answer was lost, and only one this workflow made",
     '        problems.append("a draft asked for whose answer was lost is left on the tag, or a draft somebody else made could be deleted")',
     '        pass'),
    ("Attach takes off exactly what it attached when it stops partway, and only that",
     'if "trap undo EXIT" not in text or',
     'if False and "trap undo EXIT" not in text or'),
    ("the guard asks about whoever started this run of it",
     '        problems.append("the guard does not ask about the account that started this run of it")',
     '        pass'),
    ("every job that enters an environment asks first who started it, exactly as written down",
     'if (job.get("steps") or [])[:2] != STARTER_STEPS or "continue-on-error" in job:',
     'if False:'),
    ("no job that enters an environment ignores its own failures",
     'if (job.get("steps") or [])[:2] != STARTER_STEPS or "continue-on-error" in job:',
     'if (job.get("steps") or [])[:2] != STARTER_STEPS:'),
    ("release.yml reaches no secret by index or all at once",
     '            problems.append("release.yml reaches the secrets as [%s], not by name" % " ".join(expression.split()))',
     '            pass'),
    ("release.yml hands no workflow every secret",
     '        problems.append("release.yml hands every secret to a workflow it calls")',
     '        pass'),
    ("the Entra app's service principal: no password and no certificate",
     ', "service_principal_password_credentials",\n                 "service_principal_key_credentials"):',
     '):'),
    ("the Actions settings: actions named by a full commit",
     'return [] if seen == ACTIONS_PERMISSIONS else',
     'return [] if True else'),
    ("the administrators written down",
     'return [] if seen == ADMINISTRATORS else',
     'return [] if True else'),
    ("no secret stored under a name an older run reads",
     'problems = ["%s holds %s, a name an older run of release.yml reads" % (where, n) for n in sorted(names & RETIRED_SECRETS)]',
     'problems = []'),
    ("no secret stored anywhere but under the names written down for its level",
     '    if others:\n        problems.append("%s holds %s, which nothing written down here reads"',
     '    if False:\n        problems.append("%s holds %s, which nothing written down here reads"'),
    ("no signing value stored outside the release environment",
     'for n in sorted((names & RELEASE_SECRETS) - allowed)]',
     'for n in []]'),
    ("the repository may hold no secret at all",
     'judge_secret_names(listed, "the repository", REPOSITORY_SECRETS)',
     'judge_secret_names(listed, "the repository", RELEASE_SECRETS)'),
    ("the organisation may share no secret at all",
     'judge_secret_names(listed, "the organisation", ORGANISATION_SECRETS)',
     'judge_secret_names(listed, "the organisation", RELEASE_SECRETS)'),
    ("an environment job: no step carries on whatever it meets",
     'if "continue-on-error" in step:',
     'if False:'),
    ("an environment job: no step runs when an earlier one failed",
     'if STATUS_FUNCTIONS.search(str(step.get("if", ""))):',
     'if False:'),
    ("an environment job: success() is a status function too",
     '(?:success|always|failure|cancelled)',
     '(?:always|failure|cancelled)'),
    ("an environment job: a status function in any case",
     r'cancelled)\s*\(", re.I)',
     r'cancelled)\s*\(")'),
    ("an environment job: every step a mapping",
     '                problems.append("%s has a step that is not a mapping: %s" % (name, json.dumps(step)))',
     '                pass'),
    ("an environment job: nothing set for the whole job but what is written down",
     'extra = names_of(job) - ENVIRONMENT_JOB_KEYS\n        if extra:',
     'extra = set()\n        if extra:'),
    ("an environment job: its runner written down",
     'if job.get("runs-on") != ENVIRONMENT_JOB_RUNNERS[name]:',
     'if False:'),
    ("an environment job: no environment set for its steps but what is written down",
     'if names is None or names - ENVIRONMENT_JOB_ENV[name]:',
     'if False:'),
    ("release.yml: nothing set for every job but what is written down",
     'extra = names_of(doc) - WORKFLOW_KEYS',
     'extra = set()'),
    ("release.yml: no environment given every job but what is written down",
     'if names is None or names - WORKFLOW_ENV:',
     'if False:'),
    ("the starter steps come first, and not anywhere in the job",
     '(job.get("steps") or [])[:2] != STARTER_STEPS',
     'not all(s in (job.get("steps") or []) for s in STARTER_STEPS)'),
    ("the starter checkout step is held as well as the question",
     '(job.get("steps") or [])[:2] != STARTER_STEPS',
     '(job.get("steps") or [])[1:2] != STARTER_STEPS[1:]'),
    ("no job calls a workflow from another repository: read by pattern",
     '            if m and job:\n                calls.append((job, m.group(1)))',
     '            pass'),
    ("no job calls a workflow from another repository: read as YAML reads it",
     '            calls += [(str(job_name), str(job["uses"])) for job_name, job in parsed_jobs(doc) if "uses" in job]',
     '            pass'),
    ("no other workflow enters an environment: read by pattern",
     'reads = [jobs_in_environment(text)]',
     'reads = []'),
    ("no other workflow enters an environment: read as YAML reads it",
     '            reads.append(jobs_in_environment_parsed(doc))',
     '            pass'),
    ("who starts a release: the login in any case",
     'if name.lower() == str(login).lower():',
     'if name == str(login):'),
    ("--may-start exits 1 for an account it refuses",
     '        return 1 if problems else 0\n',
     '        return 0\n'),
    ("an error GitHub gives, other than hiding a setting, fails the run",
     '            if not hidden:\n                raise',
     '            if not hidden:\n                return'),
    ("GitHub answering anything at all is not taken for hiding a setting",
     'hidden = e.code in (401, 403) or (e.code == 404 and settings_hidden[:1] != [False])',
     'hidden = True'),
    ("a 404 is hiding a setting only where the Actions settings were hidden too",
     'hidden = e.code in (401, 403) or (e.code == 404 and settings_hidden[:1] != [False])',
     'hidden = e.code in (401, 403, 404)'),
    ("settings that could not be read fail the run",
     'say("FAIL", "the settings could not all be read: %s" % e)',
     'say("UNSEEN", "the settings could not all be read: %s" % e)'),
    ("--need-admin: a setting GitHub did not show fails",
     '        if need_admin:\n            say("FAIL"',
     '        if False:\n            say("FAIL"'),
    ("--need-admin: an administrator's setting hidden goes through it",
     'unseen(what, "GitHub shows this only to an administrator',
     '(lambda what, why: say("UNSEEN", what))(what, "GitHub shows this only to an administrator'),
    ("--need-admin: a ruleset's bypass list hidden goes through it",
     'unseen("ruleset [%s]" % summary["name"], ',
     '(lambda what, why: say("UNSEEN", what))("ruleset [%s]" % summary["name"], '),
    ("--need-admin: the organisation's two-factor rule hidden goes through it",
     'unseen("the organisation requires two-factor sign-in of every member", ',
     '(lambda what, why: say("UNSEEN", what))("the organisation requires two-factor sign-in of every member", '),
    ("--need-admin is handed to run()",
     'azure=args.azure, need_admin=args.need_admin,',
     'azure=args.azure,'),
    ("every list is read to its last page",
     'url = found.group(1) if found else None',
     'url = None'),
    ("a list's pages are joined",
     '            whole += value\n',
     '            pass\n'),
    ("the pages of a list of secrets or of environments are joined",
     '                    whole[key] += value[key]',
     '                    pass'),
    ("a page of another shape than the first is refused",
     '            raise ValueError("%s answered a page of another shape than its first" % path)',
     '            pass'),
    ("a list of secrets is read only where it is a list",
     '    if not isinstance(secrets, list) or not all(isinstance(s, dict) for s in secrets):\n        return None, [',
     '    secrets = secrets if isinstance(secrets, list) else []\n    if False:\n        return None, ['),
    ("a list of secrets is read only where it holds as many as GitHub counts",
     '    if listed.get("total_count") != len(secrets):',
     '    if False:'),
    ("every environment but release holds no secret",
     '        problems += judge_secret_names(held[name], "the %s environment" % name, OTHER_ENVIRONMENT_SECRETS)',
     '        pass'),
    ("the environments are read only where GitHub lists them whole",
     '        if not isinstance(names, list) or listed.get("total_count") != len(names) or not all(isinstance(n, str) for n in names):',
     '        if not isinstance(names, list):'),
    ("the organisation's Dependabot secrets hold no signing name",
     '            for n in sorted(names & (RELEASE_SECRETS | RETIRED_SECRETS))]',
     '            for n in sorted(names & set())]'),
    ("an action that starts anything when the job starts is refused",
     '            if early:\n                problems.append(',
     '            if False:\n                problems.append('),
    ("an action's pre step is refused",
     'PRE_KEYS = ("pre", "pre-if", "pre-entrypoint")',
     'PRE_KEYS = ("pre-if", "pre-entrypoint")'),
    ("an action's pre-if is refused",
     'PRE_KEYS = ("pre", "pre-if", "pre-entrypoint")',
     'PRE_KEYS = ("pre", "pre-entrypoint")'),
    ("a container action's pre-entrypoint is refused",
     'PRE_KEYS = ("pre", "pre-if", "pre-entrypoint")',
     'PRE_KEYS = ("pre", "pre-if")'),
    ("an action whose way of running cannot be read is refused",
     '            problems.append("%s says nothing this can read about how it runs" % said)',
     '            pass'),
    ("an action that was not read is refused",
     '            problems.append("%s was not read, so whether it starts anything',
     '            (lambda *a: None)("%s was not read, so whether it starts anything'),
    ("the actions a composite action uses are judged",
     '                    judge(each, depth + 1, inside + [uses])',
     '                    pass'),
    ("a composite action is known whatever the case it is written in",
     'str(runs.get("using")).lower() != "composite"',
     'str(runs.get("using")) != "composite"'),
    ("a composite action whose steps cannot be read is refused",
     '                problems.append("%s is a composite action whose steps this cannot read" % said)',
     '                pass'),
    ("an action a composite one uses, not named by a full commit, is refused",
     '                if not PINNED_ACTION.match(each):\n                    problems.append(',
     '                if False:\n                    problems.append('),
    ("a full commit is forty characters",
     '@[0-9a-f]{40}\\Z")',
     '@[0-9a-f]+\\Z")'),
    ("a full commit is written as GitHub writes it, in lower case",
     '@[0-9a-f]{40}\\Z")',
     '@[0-9a-fA-F]{40}\\Z")'),
    ("a full commit ends the name, and no line's end follows it",
     '@[0-9a-f]{40}\\Z")',
     '@[0-9a-f]{40}$")'),
    ("an action run by a way this does not know is refused",
     '            if using not in RUNS_USING:\n                problems.append(',
     '            if False:\n                problems.append('),
    ("an action with a key in how it runs that this does not know is refused",
     '            if unknown:\n                problems.append(',
     '            if False:\n                problems.append('),
    ("a container action built from its Dockerfile is refused",
     'if using == "docker" and not str(runs.get("image")).startswith("docker://"):',
     'if False:'),
    ("a composite action's step holding a key this does not know is refused",
     ' and set(s) <= STEP_KEYS for s in steps):',
     ' for s in steps):'),
    ("no folder in an action's name is . or ..",
     'r"^(?!.*(?:^|/)\\.\\.?(?:/|@))',
     'r"^'),
    ("an action deeper than composite actions are read is refused",
     '                elif depth >= NESTED_DEPTH:',
     '                elif False:'),
    ("composite actions are read three deep and no deeper",
     'NESTED_DEPTH = 3',
     'NESTED_DEPTH = 4'),
    ("run() reads the actions a composite action uses",
     '                    waiting += [(each, depth + 1)',
     '                    waiting += [] and [(each, depth + 1)'),
    ("run() reads each action's file once",
     '                if uses in runs_of:\n                    continue',
     '                if False:\n                    continue'),
    ("run() reads no deeper than composite actions are judged",
     '                if depth < NESTED_DEPTH:',
     '                if True:'),
    ("run() asks for no file of an action not named by a full commit",
     ' if PINNED_ACTION.match(each)]',
     ']'),
    ("an empty list of administrators is not taken for the true one",
     'return collaborators != []',
     'return True'),
    ("run() asks whether GitHub showed this token the administrators",
     'judge_administrators,\n                      shown=administrators_shown)',
     'judge_administrators)'),
    ("an answer GitHub did not show this token is not judged",
     '        if shown and not shown(value) and settings_hidden[:1] != [False]:',
     '        if False:'),
    ("an empty answer is taken for hidden only where the Actions settings were hidden too",
     '        if shown and not shown(value) and settings_hidden[:1] != [False]:',
     '        if shown and not shown(value):'),
    ("--need-admin: an answer GitHub did not show this token fails",
     'unseen(what, "GitHub answered this token with an empty list',
     '(lambda what, why: say("UNSEEN", what))(what, "GitHub answered this token with an empty list'),
    ("an answer GitHub did not show this token is still named as a clause",
     '            ran.append(what)\n            unseen(what, "GitHub answered',
     '            unseen(what, "GitHub answered'),
    ("a list of secrets is read only where each is a secret",
     ' or not all(isinstance(s, dict) for s in secrets):\n        return None, [',
     ':\n        return None, ['),
    ("every action an environment job uses is read",
     '                used.add(step["uses"])',
     '                pass'),
    ("an environment job given as other than a mapping is refused",
     '            problems.append("%s is not a job release.yml can run: %s" % (name, json.dumps(job)))',
     '            pass'),
    ("--need-admin beside --tree is refused",
     '        parser.error("--need-admin asks for settings read from GitHub, and --tree reads none")',
     '        pass'),
    ("a page is read only from GitHub's API",
     'if url and (pages >= 100 or not url.startswith("https://api.github.com/")):',
     'if url and pages >= 100:'),
    ("the organisation requires two-factor sign-in",
     '[] if required is True else',
     '[] if True else'),
    ("the Entra app: no password and no certificate",
     'if app.get(kind) != []:',
     'if False:'),
    ("the Entra app: one federated credential, for the release environment of this repository",
     'elif (federated[0].get("issuer"), ',
     'elif False and (federated[0].get("issuer"), '),
    ("the Entra app: the signer role on one certificate profile",
     '\n                    or not re.match(AZURE_PROFILE_SCOPE, str(roles[0].get("scope")))):',
     '):'),
    ("the Entra app: no role but the signer role",
     '(roles[0].get("roleDefinitionName") not in AZURE_SIGNER_ROLES\n',
     '(False\n'),
    ("the Entra app: one role at most",
     'if not isinstance(roles, list) or len(roles) > 1:',
     'if not isinstance(roles, list) or len(roles) > 2:'),
    ("the Entra app: its roles are read",
     'if not isinstance(roles, list) or len(roles) > 1:',
     'if isinstance(roles, list) and len(roles) > 1:'),
    ("the Entra app: its credential trusts main and release.yml, not the environment alone",
     'want = token_subject("release")',
     'want = OIDC_SUBJECT["sub_claim_prefix"] + ":environment:release"'),
    ("the Entra app: who else holds a role on the signing account is read",
     'return problems + judge_azure_holders(app, roles)',
     'return problems'),
    ("the Entra file names the signing account",
     'if not isinstance(account, str) or not re.match(AZURE_ACCOUNT_SCOPE, account):',
     'if False:'),
    ("the Entra file's signing account is an account, and not a profile or anything else",
     ' or not re.match(AZURE_ACCOUNT_SCOPE, account):',
     ':'),
    ("the Entra file names the app's service principal",
     'if not isinstance(principal, str) or not principal:',
     'if False:'),
    ("the Entra file says its role assignments were listed whole",
     'if not isinstance(every, dict) or every.get("listed") != AZURE_LISTED:',
     'if not isinstance(every, dict):'),
    ("the Entra file: a list of role assignments that is not one is refused",
     '            problems.append("its %s role assignments are no list of them" % kind)\n            continue',
     '            continue'),
    ("the Entra file: who is eligible for a role is read as well as who holds one",
     'for kind in ("active", "eligible"):',
     'for kind in ("active",):'),
    ("the Entra file: anybody but the app holding a role that signs is refused",
     'elif signs and (kind == "eligible" or not mine):',
     'elif False:'),
    ("the Entra file: being eligible for a role that signs is refused, the app included",
     '(kind == "eligible" or not mine)',
     '(not mine)'),
    ("the Entra file: a role not read for what it may do is refused",
     '                problems.append("%s: what its role may do was not read" % said)',
     '                pass'),
    ("the Entra file: a role whose name was not read is refused",
     'if not isinstance(name, str) or not isinstance(actions, list)',
     'if not isinstance(actions, list)'),
    ("the Entra file: a role signs by its name",
     'return name in AZURE_SIGNER_ROLES or any(',
     'return any('),
    ("the Entra file: a role signs by its data actions, a custom role among them",
     'return name in AZURE_SIGNER_ROLES or any(',
     'return name in AZURE_SIGNER_ROLES or False and any('),
    ("the Entra file: a data action's wildcard is read as Azure reads it",
     'pieces, text = pattern.lower().split("*"), action.lower()',
     'pieces, text = [pattern.lower()], action.lower()'),
    ("the Entra file: a data action is read without regard to case",
     'pieces, text = pattern.lower().split("*"), action.lower()',
     'pieces, text = pattern.split("*"), action'),
    ("the Entra file: a wildcard pattern holds the action to its last piece",
     ' or not text.endswith(pieces[-1]):',
     ':'),
    ("the Entra file: the sign action Azure's signer role carries counts",
     'AZURE_SIGN_ACTIONS = ("Microsoft.CodeSigning/certificateProfiles/Sign/action",\n                      ',
     'AZURE_SIGN_ACTIONS = ('),
    ("the Entra file: the sign action written with the account in it counts",
     ',\n                      "Microsoft.CodeSigning/codeSigningAccounts/certificateProfiles/Sign/action")',
     ',)'),
    ("the Entra file: a scope of a shape this cannot place is taken to reach the signing account",
     '    if not re.match(AZURE_SCOPE_SHAPE, s):\n        return True',
     '    if False:\n        return True'),
    ("the Entra file names the subscription it listed, and the signing account is in it",
     '    if (not isinstance(within, str) or ',
     '    if False and (not isinstance(within, str) or '),
    ("the Entra file: what it names as the subscription is a subscription",
     ' or not re.match(AZURE_SUBSCRIPTION_SCOPE, within)',
     ''),
    ("the Entra file: a role on the signing account itself reaches it",
     'return (s == a or ',
     'return ('),
    ("the Entra file: a role above the signing account reaches it",
     ' or a.startswith(s + "/")',
     ''),
    ("the Entra file: a role below the signing account reaches it",
     ' or s.startswith(a + "/")',
     ''),
    ("the Entra file: a role on a management group reaches it",
     '\n            or s.startswith("/providers/microsoft.management/managementgroups/"))',
     ')'),
    ("the Entra file: a scope reaches the signing account without regard to case",
     's, a = scope.rstrip("/").lower(), str(account).lower()',
     's, a = scope.rstrip("/"), str(account)'),
    ("the Entra file: a scope this cannot read is taken to reach the signing account",
     '    if not isinstance(scope, str):\n        return True',
     '    if not isinstance(scope, str):\n        return False'),
    ("the Entra file: the app's roles are gathered from the whole list",
     '            if kind == "active" and mine:\n                ours.append(',
     '            if False:\n                ours.append('),
    ("the Entra file: the app's roles read the same in both lists",
     'if sorted(ours, key=repr) != theirs:',
     'if False:'),
    ("the Entra file: the app's role is on a profile of the signing account",
     'if not str(r.get("scope")).lower().startswith(',
     'if False and not str(r.get("scope")).lower().startswith('),
    ("the token subject names the ref",
     '"%s:environment:%s:ref:refs/heads/main:job_workflow_ref:%s" % (',
     '"%s:environment:%s:job_workflow_ref:%s" % ('),
    ("the token subject names the workflow",
     '"%s:environment:%s:ref:refs/heads/main:job_workflow_ref:%s" % (\n        OIDC_SUBJECT["sub_claim_prefix"], environment, RELEASE_WORKFLOW_REF)',
     '"%s:environment:%s:ref:refs/heads/main" % (\n        OIDC_SUBJECT["sub_claim_prefix"], environment)'),
    ("the token a job is given is held to the subject written here",
     'return [] if subject == want else ["the token this job was given',
     'return [] if True else ["the token this job was given'),
    ("each job that signs with a token holds its subject first",
     'if ((jobs.get(name) or {}).get("steps") or [])[2:3] != [token_step(name)]]',
     'if False]'),
    ("each job that signs with a token holds its subject, wherever the step sits",
     'if ((jobs.get(name) or {}).get("steps") or [])[2:3] != [token_step(name)]]',
     'if token_step(name) not in ((jobs.get(name) or {}).get("steps") or [])]'),
    ("the token is asked for its audience",
     '"%s&audience=%s" % (url, urllib.parse.quote(audience, safe=""))',
     '"%s" % (url,)'),
    ("the token is asked for only where the job may ask for one",
     '    if not url or not bearer:\n        raise ValueError("this job may not ask GitHub for a token")',
     '    if not url:\n        raise ValueError("this job may not ask GitHub for a token")'),
    ("no job but the two that sign with a token may ask for one",
     'for name, job in jobs.items() if name not in TOKEN_AUDIENCES and asks_for_a_token(job.get("permissions"))]',
     'for name, job in jobs.items() if False]'),
    ("the workflow may not let every job ask for a token",
     '    if asks_for_a_token(doc.get("permissions")):\n',
     '    if False:\n'),
    ("a token asked for by a permission that names it",
     '        return permissions.get("id-token") == "write"\n',
     '        return False\n'),
    ("a token asked for by every permission at once",
     '    return permissions is not None and permissions != "read-all"\n',
     '    return False\n'),
    ("--token-subject judges the token it read",
     '        problems = judge_token(claims, environment)\n',
     '        problems = []\n'),
    ("--token-subject exits 1 on a token it refuses",
     '            print("FAIL: %s" % problems[0])\n            return 1\n',
     '            print("FAIL: %s" % problems[0])\n            return 0\n'),
    ("a setting hidden from this token is still named as a clause",
     '            ran.append(what)\n            unseen(what, "GitHub shows this only',
     '            unseen(what, "GitHub shows this only'),
    ("--need-admin: the Entra app unread fails once anything Windows signing reads is stored",
     'stored = sorted(n for n in names if isinstance(n, str) and (n.startswith("WINDOWS_SIGNING_") or n.startswith("WINDOWS_AZURE_")))',
     'stored = sorted(n for n in names if False)'),
    ("--need-admin: the Entra app unread fails once a signing endpoint, account or profile is stored",
     '(n.startswith("WINDOWS_SIGNING_") or n.startswith("WINDOWS_AZURE_"))',
     '(n.startswith("WINDOWS_AZURE_"))'),
    ("--need-admin: the Entra app unread fails once the Azure identifiers are stored, before any signing value",
     '(n.startswith("WINDOWS_SIGNING_") or n.startswith("WINDOWS_AZURE_"))',
     '(n.startswith("WINDOWS_SIGNING_"))'),
    ("--need-admin: the Entra app unread fails where the release environment's secrets were not read",
     '    if listed is None:\n        return ["the release environment',
     '    if listed is None:\n        return [] and ["the release environment'),
    ("--need-admin: the Entra app unread fails where the release environment's secrets were not read whole",
     '        return problems + ["so the Entra app has not been read',
     '        return [] and problems + ["so the Entra app has not been read'),
    ("the Entra app unread fails only where --need-admin asks",
     'if release_listed else None) if need_admin else []',
     'if release_listed else None)'),
    ("--tree exits 1 on a failure",
     '    code = 1 if "FAIL" in results else 0',
     '    code = 0'),
    ("main() exits with what run() found",
     'reach=installations_reader(token) if token else None)\n    return code\n',
     'reach=installations_reader(token) if token else None)\n    return 0\n'),
    ("every environment but release is read, not only the first",
     'for n in names if n != "release"}',
     'for n in [m for m in names if m != "release"][:1]}'),
    ("an action's file YAML cannot read is not taken for one with no step of its own",
     'runs_of[uses] = read.get("runs") if isinstance(read, dict) else None',
     'runs_of[uses] = read.get("runs") if isinstance(read, dict) else {"using": "node24", "main": "m.js"}'),
    ("deployments: a record made before the policy was set is not held to it",
     '            if created < instant(since):\n                continue',
     '            if False:\n                continue'),
    ("deployments: a record made since the policy was set is held to it",
     '            if created < instant(since):\n                continue',
     '            if True:\n                continue'),
    ("deployments: a record made by an account not written down as starting releases is refused",
     '            if judge_starter(creator.get("login"), creator.get("id")):',
     '            if False:'),
    ("deployments: whoever made a record is held by account number as well as by login",
     '            if judge_starter(creator.get("login"), creator.get("id")):',
     '            if judge_starter(creator.get("login"), RELEASE_STARTERS.get(creator.get("login"))):'),
    ("deployments: a record from a ref other than main is asked whether it ran",
     '            if d.get("ref") != "main":\n                states = ',
     '            if False:\n                states = '),
    ("deployments: a record made in the second the policy was set is held to it",
     '            if created < instant(since):',
     '            if created <= instant(since):'),
    ("deployments: a ref is main only where it is main, not where it starts so",
     '            if d.get("ref") != "main":\n                states = ',
     '            if not str(d.get("ref")).startswith("main"):\n                states = '),
    ("deployments: whoever made a record is held by login as well as by account number",
     '            if judge_starter(creator.get("login"), creator.get("id")):',
     '            if str(creator.get("id")) not in [str(n) for n in RELEASE_STARTERS.values()]:'),
    ("deployments: a failure says it is seen after the fact and stopped nothing",
     '        problems.append("this is seen after the fact, and stopped nothing")',
     '        pass'),
    ("deployments: waiting is not taken for having run",
     'RAN = {"in_progress", "success"}',
     'RAN = {"in_progress", "success", "waiting"}'),
    ("deployments: a job that got in and then failed has run",
     'RAN = {"in_progress", "success"}',
     'RAN = {"success"}'),
    ("deployments: a record whose statuses were not read is refused",
     '                    problems.append("%s: its statuses were not read, so whether it ran is not known" % said)',
     '                    pass'),
    ("deployments: a record whose time cannot be read is refused",
     '                problems.append("%s: when it was made could not be read" % said)\n                continue',
     '                continue'),
    ("deployments: an environment's list that is not one is refused",
     '            problems.append("GitHub\'s answer for the %s environment\'s deployments is no list of them" % environment)',
     '            pass'),
    ("deployments: the window opens when the policy was first set, not after",
     'DEPLOYMENTS_SINCE = "2026-09-25T10:14:13Z"',
     'DEPLOYMENTS_SINCE = "2026-09-25T10:15:00Z"'),
    ("deployments: both signing environments are read",
     'DEPLOYMENT_ENVIRONMENTS = ("release", "linux-signing")',
     'DEPLOYMENT_ENVIRONMENTS = ("release",)'),
    ("deployments: statuses are read where the judgement turns on them",
     'for d in listed if statuses_needed(d)}',
     'for d in listed if False}'),
    ("deployments: statuses are read only where the judgement turns on them",
     'for d in listed if statuses_needed(d)}',
     'for d in listed if isinstance(d, dict)}'),
    ("deployments: a record from main needs no statuses read",
     'return deployment.get("ref") != "main" and (',
     'return ('),
    ("deployments: a record before the policy needs no statuses read",
     ' or created >= instant(since))',
     ' or True)'),
    ("deployments: a record made in the second the policy was set has its statuses read",
     ' or created >= instant(since))',
     ' or created > instant(since))'),
    ("run() keeps the release environment's secrets for the Entra app's line",
     'lambda listed: release_listed.append(listed) or judge_secret_names(',
     'lambda listed: judge_secret_names('),
    ("apps: write on actions reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("administration", "contents", "environments", "secrets", "workflows")'),
    ("apps: write on administration reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("actions", "contents", "environments", "secrets", "workflows")'),
    ("apps: write on contents reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("actions", "administration", "environments", "secrets", "workflows")'),
    ("apps: write on environments reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("actions", "administration", "contents", "secrets", "workflows")'),
    ("apps: write on secrets reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "workflows")'),
    ("apps: write on workflows reaches the route",
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets", "workflows")',
     'ROUTE_WRITES = ("actions", "administration", "contents", "environments", "secrets")'),
    ("apps: write on members reaches every repository",
     'ORGANISATION_WRITES = ("members", "organization_administration", "organization_secrets")',
     'ORGANISATION_WRITES = ("organization_administration", "organization_secrets")'),
    ("apps: write on organization_administration reaches every repository",
     'ORGANISATION_WRITES = ("members", "organization_administration", "organization_secrets")',
     'ORGANISATION_WRITES = ("members", "organization_secrets")'),
    ("apps: write on organization_secrets reaches every repository",
     'ORGANISATION_WRITES = ("members", "organization_administration", "organization_secrets")',
     'ORGANISATION_WRITES = ("members", "organization_administration")'),
    ("the pages of a list of installations are joined",
     'PAGED_KEYS = ("secrets", "environments", "installations", "repositories")',
     'PAGED_KEYS = ("secrets", "environments", "repositories")'),
    ("the pages of a list of repositories are joined",
     'PAGED_KEYS = ("secrets", "environments", "installations", "repositories")',
     'PAGED_KEYS = ("secrets", "environments", "installations")'),
    ("apps: admin counts as write",
     'WRITES = ("write", "admin")',
     'WRITES = ("write",)'),
    ("apps: an organisation write fails whatever the app is installed on",
     '        if wide:\n            problems.append(',
     '        if False:\n            problems.append('),
    ("apps: a route write on every repository fails",
     'problems.append("%s is installed on every repository, this one among them"',
     '(lambda *a: None)("%s is installed on every repository, this one among them"'),
    ("apps: this repository on an app's list, found by its number",
     'r.get("id") == REPO_NUMBER or ',
     ''),
    ("apps: this repository on an app's list, found by its name",
     ' or str(r.get("full_name")).lower() == REPO.lower()',
     ''),
    ("apps: a list read short is not taken for one without this repository",
     'elif answer.get("total_count") != len(repositories):',
     'elif False:'),
    ("apps: a list answered with none is not taken for one without this repository",
     'unread.append("%s is installed on a list of repositories GitHub answered with no list"',
     '(lambda *a: None)("%s is installed on a list of repositories GitHub answered with no list"'),
    ("apps: an installation neither on every repository nor on a list fails",
     'problems.append("%s is installed on %s, which is neither',
     '(lambda *a: None)("%s is installed on %s, which is neither'),
    ("apps: the installations are read only where GitHub lists them whole",
     '    if listed.get("total_count") != len(installations):',
     '    if False:'),
    ("apps: an installation listed with no permissions fails",
     'problems.append("%s is listed with no permissions',
     '(lambda *a: None)("%s is listed with no permissions'),
    ("apps: a list nobody read is said, not passed",
     'problems, unread = judged if isinstance(judged, tuple) else (judged, [])',
     'problems, unread = (judged[0] if isinstance(judged, tuple) else judged), []'),
    ("--need-admin: an app's list unread goes through it",
     'unseen(what, "; ".join(unread))',
     '(lambda what, why: say("UNSEEN", what))(what, "; ".join(unread))'),
    ("apps: GitHub refusing a list leaves it unread, and anything else it answers fails",
     'if e.code not in (401, 403, 404):\n                    raise ValueError(',
     'if False:\n                    raise ValueError('),
    ("apps: an empty list of them is taken for hidden only where the Actions settings were",
     'shown=lambda read: not (isinstance(read[0], dict) and read[0].get("total_count") == 0))',
     'shown=None)'),
    ("apps: their lists are read with their own token",
     'get(url, with_headers=True, token=token))',
     'get(url, with_headers=True))'),
    ("a token handed to get() is the one it sends",
     'token = token or os.environ.get("GH_TOKEN")',
     'token = os.environ.get("GH_TOKEN")'),
    ("TW_INSTALLATIONS_TOKEN is handed to run()",
     'reach=installations_reader(token) if token else None)',
     'reach=None)'),
] + [unwired(call) for call in (
    'clause("release.yml is started by hand',
    'clause("only release.yml\'s tag, sign-macos',
    'clause("the signature check holds a Linux signature',
    'clause("no job in release.yml restores',
    'clause("no workflow names an Azure client secret',
    'clause("no workflow calls a reusable workflow',
    'clause("release.yml reads the signing values',
    'clause("the guard refuses anybody',
    'clause("what is written here lets nobody make a tag',
    'clause("every tag that stands is named',
    'clause("every job that enters an environment asks',
    'clause("each job that signs with a token',
    'clause("no job that enters an environment runs on',
    'clause("a release is a draft until',
    'clause("the Attach step is the one written down here',
    'clause("the pinned signing action',
    'clause("the release environment admits',
    'clause("since the policy was set, only an account',
    'clause("every ruleset written down',
    'clause("ruleset [%s] is as written here"',
    'clause("main is protected',
    'clause("the token Azure trusts',
    'unless_hidden("every action a workflow uses',
    'unless_hidden("the repository is administered',
    'unless_hidden("the release environment holds',
    'unless_hidden("the repository holds no secret',
    'unless_hidden("the organisation shares no secret',
    'unless_hidden("no environment but release holds a secret"',
    'unless_hidden("the repository holds no Dependabot secret"',
    'unless_hidden("the organisation holds no Dependabot secret',
    'clause("no action a job in an environment uses runs a step before the starter steps", judge_no_pre_step(',
    'clause("the organisation requires two-factor',
    'unless_hidden("no app installed on the organisation',
    'clause("the Entra app signs in',
)]

CHECKS = [
    (SIGNATURE_CHECK, ["--self-test"], SIGNATURE_CLAUSES),
    (ROUTE_CHECK, ["--self-test", "--need-yaml"], ROUTE_CLAUSES),
]


def self_test(root, check, flags):
    done = subprocess.run([sys.executable, os.path.join(root, "scripts", check)] + flags,
                          capture_output=True, text=True, encoding="utf-8", errors="replace", timeout=900)
    return done.returncode, (done.stdout or "") + (done.stderr or "")


def workers():
    try:
        return max(1, int(os.environ.get("TW_CLAUSE_WORKERS", "4")))
    except ValueError:
        return 4


def main():
    source = sys.argv[1] if len(sys.argv) > 1 else HERE
    root = os.path.dirname(os.path.abspath(source))
    work = tempfile.mkdtemp(prefix="tw-clauses-")
    failed = False
    try:
        # Both checks, the identities and fixtures, and the workflows, which is all either self-test reads.
        base = os.path.join(work, "base")
        os.makedirs(os.path.join(base, "scripts"))
        for name in (SIGNATURE_CHECK, ROUTE_CHECK, "signing-identities.json"):
            shutil.copy(os.path.join(source, name), os.path.join(base, "scripts"))
        shutil.copytree(os.path.join(source, "signing-fixtures"), os.path.join(base, "scripts", "signing-fixtures"))
        shutil.copytree(os.path.join(root, ".github", "workflows"), os.path.join(base, ".github", "workflows"))

        for check, flags, _ in CHECKS:
            code, out = self_test(base, check, flags)
            if code != 0:
                print("FAIL: the untouched %s does not pass its own self-test, so nothing below means anything" % check)
                print(out.strip())
                return 1
            print("PASS: the untouched %s passes its own self-test" % check)

        jobs = []
        for check, flags, clauses in CHECKS:
            with open(os.path.join(source, check), encoding="utf-8") as f:
                text = f.read()
            for clause in clauses:
                name, pairs = clause[0], list(zip(clause[1::2], clause[2::2]))
                if any(text.count(old) != 1 for old, _ in pairs):
                    jobs.append((check, name, None))
                    continue
                changed = text
                for old, new in pairs:
                    changed = changed.replace(old, new)
                folder = os.path.join(work, "clause-%d" % len(jobs))
                shutil.copytree(base, folder)
                with open(os.path.join(folder, "scripts", check), "w", encoding="utf-8", newline="\n") as f:
                    f.write(changed)
                jobs.append((check, name, (folder, flags)))

        def judged(job):
            check, name, copy = job
            if copy is None:
                return "MOVED: %s: %s: the text it lives in is not in the check exactly once" % (check, name)
            code, out = self_test(copy[0], check, copy[1])
            # A self-test that dies has judged nothing, and a later change that caught what killed
            # it would turn it green; so only a self-test that ran to its end and failed counts.
            if "Traceback (most recent call last)" in out:
                return "CRASHED: %s: %s: the self-test died rather than judging: %s" % (
                    check, name, out.strip().splitlines()[-1][:200])
            if code != 0:
                return "CAUGHT: %s: %s: the self-test fails without it" % (check, name)
            return "MISSED: %s: %s: the self-test passes without it" % (check, name)

        with concurrent.futures.ThreadPoolExecutor(max_workers=workers()) as pool:
            for line in pool.map(judged, jobs):
                print(line, flush=True)
                if not line.startswith("CAUGHT"):
                    failed = True
    finally:
        shutil.rmtree(work, ignore_errors=True)
    total = sum(len(clauses) for _, _, clauses in CHECKS)
    if failed:
        print("FAIL: the self-tests do not hold every clause of the signing route's two checks")
        return 1
    print("PASS: each self-test fails with any one of its clauses taken away, %d clauses across the two checks" % total)
    return 0


if __name__ == "__main__":
    sys.exit(main())
