//! What a third party signed for us, kept as the bytes it arrived as.
//!
//! A source that only tells us the time improves our clock and proves nothing to anybody else. A
//! source that signs over a nonce we generated proves, to a stranger who trusts neither of us, that
//! the exchange happened after we chose that nonce. Those are two different things and this type is
//! the second one.
//!
//! It sits in this crate because the clock model and the receipt both need it and neither is
//! allowed to see the other. The source client fills it in, the model ignores it, and the receipt
//! issuer lifts it into an evidence entry.
//!
//! It is raw bytes and a claim about them. It is not a bound and it never becomes one. Whether
//! these bytes prove not-earlier-than, not-later-than, or an authenticated corridor is decided by
//! the issuer and checked by the validator, not asserted here.

use crate::time::{Nanos, UnixNanos};

/// A signed response from a source, with the nonce it was signed over.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Attestation {
    /// The bytes we chose and sent, which the source signed over.
    ///
    /// This is what stops a response being replayed at us. It is generated by the caller, before
    /// the request goes out, and it is carried here so the receipt can show what was asked as well
    /// as what came back.
    pub nonce: Vec<u8>,

    /// The response exactly as it arrived, in the source's own wire format.
    ///
    /// Kept as bytes rather than parsed because a verifier has to check the signature over the
    /// bytes the source actually signed. Anything we re-encode is a different document.
    pub blob: Vec<u8>,

    /// The instant the response itself asserts, as the source stated it.
    ///
    /// This is the source's claim and not a reading of any clock of ours. A Roughtime response
    /// states a midpoint, a beacon states the instant its round was drawn, and a timestamp
    /// authority states when it signed.
    pub at: UnixNanos,

    /// Half the width of the interval the response asserts, where it asserts one.
    ///
    /// Roughtime answers with a midpoint and a radius, and the radius is the whole of what makes
    /// the answer checkable: without it a corridor entry cannot say what interval it supports and
    /// nothing downstream can test it against the interval the receipt claims. A beacon and a
    /// timestamp authority assert an instant rather than an interval, so this is `None` for them.
    pub radius: Option<Nanos>,
}

impl Attestation {
    /// An attestation asserting a single instant, with no interval around it.
    #[must_use]
    pub fn at_instant(nonce: Vec<u8>, blob: Vec<u8>, at: UnixNanos) -> Self {
        Self {
            nonce,
            blob,
            at,
            radius: None,
        }
    }

    /// An attestation asserting `at` plus or minus `radius`.
    #[must_use]
    pub fn over_interval(nonce: Vec<u8>, blob: Vec<u8>, at: UnixNanos, radius: Nanos) -> Self {
        Self {
            nonce,
            blob,
            at,
            radius: Some(radius.max(0)),
        }
    }

    /// The earliest instant this attestation is consistent with.
    #[must_use]
    pub fn earliest(&self) -> UnixNanos {
        self.at - self.radius.unwrap_or(0).max(0)
    }

    /// The latest instant this attestation is consistent with.
    #[must_use]
    pub fn latest(&self) -> UnixNanos {
        self.at + self.radius.unwrap_or(0).max(0)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::time::NANOS_PER_MILLI;

    #[test]
    fn an_instant_attestation_is_its_own_earliest_and_latest() {
        let a = Attestation::at_instant(vec![1, 2], vec![3, 4], UnixNanos(1_000));
        assert_eq!(a.earliest(), UnixNanos(1_000));
        assert_eq!(a.latest(), UnixNanos(1_000));
    }

    #[test]
    fn a_radius_widens_the_interval_both_ways() {
        let a = Attestation::over_interval(
            vec![1],
            vec![2],
            UnixNanos(1_000_000_000),
            3 * NANOS_PER_MILLI,
        );
        assert_eq!(a.latest() - a.earliest(), 6 * NANOS_PER_MILLI);
    }

    #[test]
    fn a_negative_radius_is_refused_rather_than_shrinking_the_interval() {
        let a = Attestation::over_interval(vec![], vec![], UnixNanos(0), -500);
        assert_eq!(a.radius, Some(0));
        assert_eq!(a.earliest(), a.latest());
    }
}
